
import React, { useState } from 'react';
import { AlertCircle, CheckCircle, Info, Copy, ClipboardCheck } from 'lucide-react';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { cn } from '@/lib/utils';
import { AnalysisResult, CodeIssue } from '@/utils/codeAnalysis';
import { SupportedLanguage } from '@/utils/languageUtils';

interface ResultsDisplayProps {
  result?: AnalysisResult;
  language: SupportedLanguage;
}

const ResultsDisplay: React.FC<ResultsDisplayProps> = ({ result, language }) => {
  const [copied, setCopied] = useState(false);
  
  if (!result) {
    return (
      <div className="flex flex-col items-center justify-center py-12 px-4 text-center bg-secondary/30 rounded-lg border border-border/50 backdrop-blur-sm">
        <Info className="h-12 w-12 text-muted-foreground mb-4" />
        <h3 className="text-lg font-medium">Analysis Results</h3>
        <p className="text-muted-foreground mt-2">
          Click "Analyze Code" to check your code quality and get improvement suggestions.
        </p>
      </div>
    );
  }
  
  const { issues, metrics, suggestions, score } = result;
  
  const getScoreColor = (score: number) => {
    if (score >= 80) return 'text-green-500';
    if (score >= 60) return 'text-amber-500';
    return 'text-red-500';
  };
  
  const getScoreRing = (score: number) => {
    if (score >= 80) return 'ring-green-500';
    if (score >= 60) return 'ring-amber-500';
    return 'ring-red-500';
  };
  
  const handleCopyReport = async () => {
    if (!result) return;
    
    const reportText = `
CODE QUALITY REPORT

Language: ${language.toUpperCase()}
Quality Score: ${score}/100
Lines of Code: ${metrics.linesOfCode}
Complexity: ${metrics.complexity}/10
Maintainability: ${metrics.maintainability}/100

ISSUES FOUND:
${issues.length > 0 
  ? issues.map(issue => `- ${issue.severity.toUpperCase()} Line ${issue.line}: ${issue.message}`).join('\n')
  : '- No issues found. Great job!'}

IMPROVEMENT SUGGESTIONS:
${suggestions.map(suggestion => `- ${suggestion}`).join('\n')}

Generated by Quality Maven
`;
    
    try {
      await navigator.clipboard.writeText(reportText);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      console.error('Failed to copy report to clipboard:', err);
    }
  };
  
  return (
    <div className="rounded-lg glass-card overflow-hidden animate-scale-in">
      <div className="p-4 md:p-6">
        <div className="flex flex-col md:flex-row items-center justify-between mb-6">
          <div className="flex items-center space-x-4 mb-4 md:mb-0">
            <div className={cn(
              "flex items-center justify-center w-16 h-16 rounded-full bg-background ring-4",
              getScoreRing(score)
            )}>
              <span className={cn("text-xl font-bold", getScoreColor(score))}>
                {score}
              </span>
            </div>
            <div>
              <h3 className="text-lg font-semibold">Code Quality Score</h3>
              <p className="text-sm text-muted-foreground">
                Based on issues, metrics, and best practices
              </p>
            </div>
          </div>
          <div className="flex items-center space-x-4">
            <div className="text-center px-3 py-2">
              <p className="text-xl font-semibold">{metrics.linesOfCode}</p>
              <p className="text-xs text-muted-foreground">Lines</p>
            </div>
            <div className="text-center px-3 py-2">
              <p className="text-xl font-semibold">{metrics.complexity}/10</p>
              <p className="text-xs text-muted-foreground">Complexity</p>
            </div>
            <div className="text-center px-3 py-2">
              <p className="text-xl font-semibold">{metrics.maintainability}/100</p>
              <p className="text-xs text-muted-foreground">Maintainability</p>
            </div>
          </div>
        </div>
        
        <Tabs defaultValue="issues" className="w-full">
          <TabsList className="grid w-full grid-cols-3 bg-secondary/30">
            <TabsTrigger value="issues">Issues</TabsTrigger>
            <TabsTrigger value="suggestions">Suggestions</TabsTrigger>
            <TabsTrigger value="report">Report</TabsTrigger>
          </TabsList>
          
          <TabsContent value="issues" className="mt-4 max-h-64 overflow-y-auto p-2">
            {issues.length > 0 ? (
              <ul className="space-y-3">
                {issues.map((issue, index) => (
                  <IssueItem key={index} issue={issue} />
                ))}
              </ul>
            ) : (
              <div className="flex flex-col items-center justify-center py-8 px-4 text-center">
                <CheckCircle className="h-10 w-10 text-green-500 mb-3" />
                <p className="font-medium">No issues found. Great job!</p>
              </div>
            )}
          </TabsContent>
          
          <TabsContent value="suggestions" className="mt-4 max-h-64 overflow-y-auto p-2">
            <ul className="space-y-3">
              {suggestions.map((suggestion, index) => (
                <li 
                  key={index}
                  className="flex items-start p-3 rounded-md bg-secondary/40"
                >
                  <Info className="h-5 w-5 text-primary mr-3 flex-shrink-0 mt-0.5" />
                  <span>{suggestion}</span>
                </li>
              ))}
            </ul>
          </TabsContent>
          
          <TabsContent value="report" className="mt-4 relative">
            <div className="absolute top-0 right-0 p-2">
              <button
                onClick={handleCopyReport}
                className="flex items-center space-x-1 px-2 py-1 rounded-md text-xs bg-primary/10 text-primary hover:bg-primary/20 transition-colors"
              >
                {copied ? (
                  <ClipboardCheck className="h-4 w-4" />
                ) : (
                  <Copy className="h-4 w-4" />
                )}
                <span>{copied ? 'Copied!' : 'Copy'}</span>
              </button>
            </div>
            
            <div className="font-mono text-xs leading-relaxed bg-secondary/40 p-4 rounded-md overflow-x-auto max-h-64 overflow-y-auto">
              <p className="font-bold mb-2">CODE QUALITY REPORT</p>
              <p className="mb-4">
                Language: {language.toUpperCase()}<br />
                Quality Score: {score}/100<br />
                Lines of Code: {metrics.linesOfCode}<br />
                Complexity: {metrics.complexity}/10<br />
                Maintainability: {metrics.maintainability}/100
              </p>
              
              <p className="font-bold mb-1">ISSUES FOUND:</p>
              {issues.length > 0 ? (
                <ul className="mb-4 pl-4">
                  {issues.map((issue, index) => (
                    <li key={index}>
                      - {issue.severity.toUpperCase()} Line {issue.line}: {issue.message}
                    </li>
                  ))}
                </ul>
              ) : (
                <p className="mb-4 pl-4">- No issues found. Great job!</p>
              )}
              
              <p className="font-bold mb-1">IMPROVEMENT SUGGESTIONS:</p>
              <ul className="pl-4">
                {suggestions.map((suggestion, index) => (
                  <li key={index}>- {suggestion}</li>
                ))}
              </ul>
              
              <p className="mt-4 text-muted-foreground">Generated by Quality Maven</p>
            </div>
          </TabsContent>
        </Tabs>
      </div>
    </div>
  );
};

const IssueItem: React.FC<{ issue: CodeIssue }> = ({ issue }) => {
  const getSeverityIcon = (severity: string) => {
    switch (severity) {
      case 'error':
        return <AlertCircle className="h-5 w-5 text-red-500 mr-3 flex-shrink-0" />;
      case 'warning':
        return <AlertCircle className="h-5 w-5 text-amber-500 mr-3 flex-shrink-0" />;
      default:
        return <Info className="h-5 w-5 text-blue-500 mr-3 flex-shrink-0" />;
    }
  };
  
  return (
    <li className="flex items-start p-3 rounded-md bg-secondary/40">
      {getSeverityIcon(issue.severity)}
      <div>
        <div className="flex items-center space-x-2">
          <span className="text-xs bg-secondary/80 px-1.5 py-0.5 rounded text-muted-foreground">
            Line {issue.line}
          </span>
          <span className="text-xs bg-secondary/80 px-1.5 py-0.5 rounded text-muted-foreground">
            {issue.code}
          </span>
        </div>
        <p className="mt-1">{issue.message}</p>
      </div>
    </li>
  );
};

export default ResultsDisplay;
